### ISSUE TITLE
求live demo的代码

### ISSUE THREAD

**Issue by fonglezen** [sinchang/vue-social-share#1]
rt.

**Comment by sinchang** [comment]
https://github.com/sinchang/vue-social-share/tree/master/example

**Comment by SoloJiang** [comment]
![image](https://user-images.githubusercontent.com/14757289/28361678-26bd35bc-6cac-11e7-914c-ad37a362b453.png)
![image](https://user-images.githubusercontent.com/14757289/28361701-336d1d86-6cac-11e7-82af-2038eb834cf2.png)
![image](https://user-images.githubusercontent.com/14757289/28361714-3d3884c2-6cac-11e7-97de-70c28bf971c0.png)
无法正常使用

**Comment by sinchang** [comment]
@SoloJiang 麻烦提供下报错信息

**Comment by SoloJiang** [comment]
没有任何报错，当config按Read.me中填写时，连第三张图的渲染也没有，查看控制台，渲染了div.social-share但是高度为0，里面没有任何内容。

**Comment by sinchang** [comment]
```
components: {
  Share
}
```
没有使用 Vue.use(Share) 的话，需要声明 component

**Comment by SoloJiang** [comment]
使用了Vue.use(Share)，是在main.js中import并use的

**Comment by SoloJiang** [comment]
直接抄了你的源码😂就好了

**Comment by ruoshui1314** [comment]
hello.
`import 'social-share.js/dist/css/share.min.css'`
把这段代码放在main.js里面就好．我本地这样是ok的．
