### ISSUE TITLE
Compatible with IE

### ISSUE THREAD

**Issue by viclilei1921** [sinchang/vue-social-share#3]
[Vue warn]: Error in mounted hook: "TypeError: 无法获取未定义或 null 引用的属性“appendChild”"

**Comment by sinchang** [comment]
请问你的 IE 版本多少

**Comment by viclilei1921** [comment]
我的IE版本是IE11

**Comment by qiqihaobenben** [comment]
这是share.js的就存在的问题，已经给share.js提了pr,就一行代码的事。
