### ISSUE TITLE
那些图标出不来

### ISSUE THREAD

**Issue by huangche007** [sinchang/vue-social-share#5]
我在main.js中引入该插件:
`import Share from 'vue-social-share'

Vue.use(Share)`

然后在其他组件中使用这个share插件，发现图标没有出来

**Comment by sinchang** [comment]
这个问题解决了吗？

**Comment by huangche007** [comment]
@sinchang 解决了，那个css文件忘记引入了，不过我使用这个插件自定义分享内容无效

**Comment by sinchang** [comment]
现在还不支持通过异步获取数据去设置

**Comment by huangche007** [comment]
@sinchang OK，不过我已经搞定了，没有使用你这个插件实现的，改天我也封装一个

**Comment by kkkkh** [comment]
请问如何引入css

**Comment by sunlei4076** [comment]
@huangche007 
请问如何引入css
