### ISSUE TITLE
css 字体加载错误？

### ISSUE THREAD

**Issue by Seaony** [sinchang/vue-social-share#8]
你 package 里的加载的字体地址是相对路径，需要写成绝对路径，不然无法加载字体，我也没办法发pr。

**Comment by Seaony** [comment]
overtrue 包里的 css 样式就是这样

**Comment by sinchang** [comment]
推荐 https://github.com/nicolasbeauvais/vue-social-sharing

**Comment by Seaony** [comment]
thx ~
